<?php
defined( 'ABSPATH' ) || exit;

$config             = array();
$config['slug']     = '_xlwcty_coupon';
$config['title']    = 'Dynamic Coupons';
$config['instance'] = require( __DIR__ . '/instance.php' );
$config['fields']   = array(
	'id'                     => $config['slug'],
	'position'               => 85,
	'xlwcty_accordion_head'  => 'Advanced',
	'xlwcty_accordion_title' => $config['title'],
	'xlwcty_icon'            => 'xlwcty-fa xlwcty-fa-ticket',
	'fields'                 => array(
		array(
			'name'                       => __( 'Enable', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'                         => $config['slug'] . '_enable',
			'type'                       => 'xlwcty_switch',
			'row_classes'                => array( 'xlwcty_is_enable' ),
			'label'                      => array(
				'on'  => __( 'Yes', 'thank-you-page-for-woocommerce-nextmove' ),
				'off' => __( 'No', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'before_row'                 => array( 'XLWCTY_Admin_CMB2_Support', 'cmb_before_row_cb' ),
			'xlwcty_accordion_title'     => $config['title'],
			'xlwcty_component'           => $config['slug'],
			'xlwcty_is_accordion_opened' => false,
			'after'                      => include_once __DIR__ . '/help.php',
		),
		array(
			'id'               => $config['slug'] . '_select',
			'name'             => __( 'Select Coupon', 'thank-you-page-for-woocommerce-nextmove' ),
			'type'             => 'select',
			'desc'             => __( 'Don\'t forget to check this coupon\'s <a href="{coupon_link}">usage restrictions</a>. NextMove does not restrict coupons based on campaign rules. This responsibility lies with native coupon settings.', 'thank-you-page-for-woocommerce-nextmove' ),
			'row_classes'      => array( 'xlwcty_cmb2_chosen', 'xlwcty_cmb2_coupon' ),
			'show_option_none' => __( 'Choose a Coupon', 'thank-you-page-for-woocommerce-nextmove' ),
			'options_cb'       => array( 'XLWCTY_Admin_CMB2_Support', 'get_coupons_selected' ),
			'attributes'       => array(
				'data-pre-data'          => wp_json_encode( xlwcty_Common::get_coupons( true ) ),
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Heading', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_heading',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_no_border' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Heading font size', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_heading_font_size',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_combine_3_field_start', 'xlwcty_pt0' ),
			'before'      => '<p>Font Size (px)</p>',
			'attributes'  => array(
				'type'                   => 'number',
				'min'                    => '0',
				'pattern'                => '\d*',
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Heading color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_heading_color',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_combine_3_field_middle', 'xlwcty_pt0' ),
			'before'      => '<p>Color</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Heading alignment', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_heading_alignment',
			'type'        => 'select',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_combine_3_field_end' ),
			'before'      => '<p>Alignment</p>',
			'options'     => array(
				'left'   => __( 'Left', 'thank-you-page-for-woocommerce-nextmove' ),
				'center' => __( 'Center', 'thank-you-page-for-woocommerce-nextmove' ),
				'right'  => __( 'Right', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Description', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_desc',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'type'        => 'textarea_small',
			'row_classes' => array( 'xlwcty_no_border' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Description alignment', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_desc_alignment',
			'type'        => 'select',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_select_small' ),
			'before'      => '<p>Alignment</p>',
			'options'     => array(
				'left'   => __( 'Left', 'thank-you-page-for-woocommerce-nextmove' ),
				'center' => __( 'Center', 'thank-you-page-for-woocommerce-nextmove' ),
				'right'  => __( 'Right', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Coupon Code', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_font_size',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_combine_2_field_start' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Font Size (px)</p>',
			'attributes'  => array(
				'type'                   => 'number',
				'min'                    => '0',
				'pattern'                => '\d*',
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Coupon Text/ Border Color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_color',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_combine_2_field_end' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Text/ Border Color</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Button', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_text',
			'type'        => 'text',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'row_classes' => array( 'xlwcty_no_border' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Text</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Button Link', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Use ', 'thank-you-page-for-woocommerce-nextmove' ) . ' {{home_url}}, {{shop_url}} ' . __( 'for dynamic links.', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_link_immediate_click',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Link</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Button Font Size', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_font_size',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_select_small', 'xlwcty_combine_3_field_start', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Font Size (px)</p>',
			'attributes'  => array(
				'type'                   => 'number',
				'min'                    => '1',
				'pattern'                => '\d*',
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Button Text Color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_color',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_combine_3_field_middle', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Text Color</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Button Background Color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_bg_color',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_hide_label', 'xlwcty_combine_3_field_end', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Background Color</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Personalize Coupon', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_personalize',
			'row_classes' => array( 'xlwcty_no_border' ),
			'type'        => 'radio_inline',
			'options'     => array(
				'yes' => __( 'Yes', 'thank-you-page-for-woocommerce-nextmove' ),
				'no'  => __( 'No', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Coupon Format', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_format',
			'type'        => 'text',
			'desc'        => 'This will generate a new Coupon in above custom format.<br/>Use <a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags</a> list to generate Personalized Coupons.',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Format</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_personalize',
				'data-xlwcty-conditional-value' => 'yes',
			),
		),
		array(
			'name'        => __( 'Coupon Expiry', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'expiry in days', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_expiry',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Expiry</p>',
			'after'       => '<p class="xlwcty_mt5 xlwcty_mb5">This will set a new expiry date of personalised coupon based on order date. If left blank, expiry date of selected coupon will be used if available otherwise no expiry.</p>',
			'attributes'  => array(
				'type'                          => 'number',
				'min'                           => '1',
				'pattern'                       => '\d*',
				'data-conditional-id'           => $config['slug'] . '_enable',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_personalize',
				'data-xlwcty-conditional-value' => 'yes',
			),
		),
		array(
			'name'        => __( 'Display Coupon', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_display',
			'type'        => 'radio_inline',
			'row_classes' => array( 'xlwcty_border_top', 'xlwcty_no_border' ),
			'options'     => array(
				'immediate' => __( 'Immediate', 'thank-you-page-for-woocommerce-nextmove' ),
				'button'    => __( 'Click on button', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Description after coupon displayed', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_desc_after_click',
			'type'        => 'textarea_small',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Description after coupon displayed</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_display',
				'data-xlwcty-conditional-value' => 'button',
			),
		),
		array(
			'name'        => __( 'Button Text after coupon displayed', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_text_after_click',
			'type'        => 'text',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Button Text after coupon displayed</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_display',
				'data-xlwcty-conditional-value' => 'button',
			),
		),
		array(
			'name'        => __( 'Button Link after coupon displayed', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Use ', 'thank-you-page-for-woocommerce-nextmove' ) . ' {{home_url}}, {{shop_url}} ' . __( 'for dynamic links.', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_link_after_click',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Button Link after coupon displayed</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_display',
				'data-xlwcty-conditional-value' => 'button',
			),
		),
		array(
			'name'        => __( 'Border', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_border_style',
			'type'        => 'select',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_select_small', 'xlwcty_combine_3_field_start' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Style</p>',
			'options'     => array(
				'dotted' => __( 'Dotted', 'thank-you-page-for-woocommerce-nextmove' ),
				'dashed' => __( 'Dashed', 'thank-you-page-for-woocommerce-nextmove' ),
				'solid'  => __( 'Solid', 'thank-you-page-for-woocommerce-nextmove' ),
				'double' => __( 'Double', 'thank-you-page-for-woocommerce-nextmove' ),
				'none'   => __( 'None', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Border Width', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_border_width',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_combine_3_field_middle' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Width (px)</p>',
			'attributes'  => array(
				'type'                   => 'number',
				'min'                    => '0',
				'pattern'                => '\d*',
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Border Color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_border_color',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_combine_3_field_end', 'xlwcty_border_top' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Color</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Background', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Component background color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_component_bg',
			'type'        => 'colorpicker',
			'row_classes' => array(),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'       => __( 'Hide for Repeat Customers', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'       => __( 'If set to "Yes", dynamic coupon component won\'t be displayed to customer if she has more than one order.', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'         => $config['slug'] . '_hide_for_repeat_customers',
			'type'       => 'radio_inline',
			'options'    => array(
				'yes' => __( 'Yes', 'thank-you-page-for-woocommerce-nextmove' ),
				'no'  => __( 'No', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes' => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Hide on Device', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Desktop', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_hide_desktop',
			'type'        => 'checkbox',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_combine_2_field_start' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Hide on Device', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Mobile', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_hide_mobile',
			'type'        => 'checkbox',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_combine_2_field_end' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable',
				'data-conditional-value' => '1',
			),
			'after_row'   => array( 'XLWCTY_Admin_CMB2_Support', 'cmb_after_row_cb' ),
		),
	),
);
$config['default']  = array(
	'selected_coupon'           => '',
	'heading'                   => __( 'You unlocked a new coupon...', 'thank-you-page-for-woocommerce-nextmove' ),
	'heading_font_size'         => '20',
	'heading_color'             => '#1291ff',
	'heading_alignment'         => 'center',
	'desc'                      => __( 'Hi {{customer_first_name}}, as a way of saying thanks for shopping with {{shop_title}} today, here is a coupon for {{coupon_value}} off your next purchase in the next month.', 'thank-you-page-for-woocommerce-nextmove' ),
	'desc_alignment'            => 'center',
	'format_font'               => '26',
	'format_color'              => '#1291ff',
	'btn_txt'                   => 'Shop Now',
	'btn_link_immediate_after'  => '{{shop_url}}',
	'btn_font_size'             => '20',
	'btn_color'                 => '#ffffff',
	'btn_bg_color'              => '#1291ff',
	'personalize'               => 'yes',
	'format'                    => 'welcome-{{customer_first_name}}',
	'exp_days'                  => '',
	'display_coupon'            => 'immediate',
	'desc_after'                => __( "Hi {{customer_first_name}}, as a way of saying thanks for shopping with {{shop_title}} today, here is a coupon for {{coupon_value}} off your next purchase in the next month.\n<b>Expires on: {{coupon_expiry_date}}</b>", 'thank-you-page-for-woocommerce-nextmove' ),
	'btn_txt_after'             => 'Start Shoppping',
	'btn_link_after'            => '{{shop_url}}',
	'border_style'              => 'solid',
	'border_width'              => '1',
	'border_color'              => '#d9d9d9',
	'component_bg_color'        => '#ffffff',
	'hide_for_repeat_customers' => 'no',
);

return $config;
