<?php
$customizer_data = [
	'wfacp_form' => [
		'wfacp_form_section_embed_forms_2_disable_steps_bar'                => false,
		'wfacp_form_section_embed_forms_2_select_type'                      => "tab",
		'wfacp_form_section_text_below_placeorder_btn'                      => __( "* 100% Secure &amp; Safe Payments *", 'woofunnels-aero-checkout' ),
		'wfacp_form_section_embed_forms_2_step_alignment'                   => "center",
		'wfacp_form_section_embed_forms_2_step_form_max_width'              => '450',
		'wfacp_form_section_embed_forms_2_active_step_bg_color'             => '#4c4c4c',
		'wfacp_form_section_embed_forms_2_active_step_text_color'           => '#ffffff',
		'wfacp_form_section_embed_forms_2_active_step_count_bg_color'       => '#ffffff',
		'wfacp_form_section_embed_forms_2_active_step_count_border_color'   => '#ffffff',
		'wfacp_form_section_embed_forms_2_active_step_tab_border_color'     => '#f58e2d',
		'wfacp_form_section_embed_forms_2_inactive_step_bg_color'           => '#f2f2f2',
		'wfacp_form_section_embed_forms_2_inactive_step_text_color'         => '#979090',
		'wfacp_form_section_embed_forms_2_inactive_step_count_bg_color'     => 'rgba(255,255,255,0)',
		'wfacp_form_section_embed_forms_2_inactive_step_count_text_color'   => '#d1d1d1',
		'wfacp_form_section_embed_forms_2_inactive_step_count_border_color' => '#d1d1d1',
		'wfacp_form_section_embed_forms_2_inactive_step_tab_border_color'   => '#ededed',
		'wfacp_form_section_embed_forms_2_active_step_count_text_color'     => '#4c4c4c',
		'wfacp_form_section_embed_forms_2_step_heading_font_size'           => [
			'desktop'      => '15',
			'tablet'       => '14',
			'mobile'       => '14',
			'desktop-unit' => 'px',
			'tablet-unit'  => 'px',
			'mobile-unit'  => 'px',
		],
		'wfacp_form_form_fields_1_embed_forms_2_billing_first_name'         => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_billing_last_name'          => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_billing_city'               => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_billing_postcode'           => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_billing_country'            => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_billing_state'              => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_shipping_city'              => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_shipping_postcode'          => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_shipping_country'           => 'wfacp-col-left-half',
		'wfacp_form_form_fields_1_embed_forms_2_shipping_state'             => 'wfacp-col-left-half',
		'wfacp_form_section_embed_forms_2_field_border_width'               => '1',
		'wfacp_form_section_embed_forms_2_btn_order-place_bg_color'         => '#f58e2d',
		'wfacp_form_section_embed_forms_2_btn_order-place_text_color'       => '#ffffff',
		'wfacp_form_section_embed_forms_2_color_type'                       => 'hover',
		'wfacp_form_section_embed_forms_2_btn_order-place_bg_hover_color'   => '#d46a06',
		'wfacp_order_summary_section_embed_forms_2_order_summary_hide_img'  => true,
		'wfacp_form_section_embed_forms_2_sec_heading_color'                => '#424141',
		'wfacp_form_section_embed_forms_2_btn_order-place_btn_font_weight'  => 'bold',
		'wfacp_form_section_embed_forms_2_field_border_color'               => '#c3c0c0',
		'wfacp_form_section_embed_forms_2_heading_font_weight'              => 'wfacp-bold',
		'wfacp_form_section_embed_forms_2_heading_fs'                       => [
			'desktop'      => '18',
			'tablet'       => '18',
			'mobile'       => '18',
			'desktop-unit' => 'px',
			'tablet-unit'  => 'px',
			'mobile-unit'  => 'px',
		],
		'wfacp_form_section_embed_forms_2_step_sub_heading_font_size'       => [
			'desktop'      => '13',
			'tablet'       => '12',
			'mobile'       => '12',
			'desktop-unit' => 'px',
			'tablet-unit'  => 'px',
			'mobile-unit'  => 'px',
		],
		'wfacp_form_section_embed_forms_2_btn_next_btn_text'                => __( 'PROCEED TO NEXT STEP  →', 'woofunnels-aero-checkout' ),
		'wfacp_form_section_embed_forms_2_btn_order-place_btn_text'         => __( 'PLACE ORDER NOW ', 'woofunnels-aero-checkout' ),
		'wfacp_form_section_payment_methods_heading'                        => __( 'Payment method', 'woofunnels-aero-checkout' ),
		'wfacp_form_section_embed_forms_2_btn_back_btn_text'                => __( 'PROCEED TO FINAL STEP →', 'woofunnels-aero-checkout' ),
	],
];

return [
	'default_customizer_value' => $customizer_data
];
