<?php
defined( 'ABSPATH' ) || exit;

$config             = array();
$config['slug']     = '_xlwcty_image';
$config['title']    = 'Image Text';
$config['instance'] = require( __DIR__ . '/instance.php' );
$config['fields']   = array(
	'id'                     => $config['slug'],
	'position'               => 35,
	'xlwcty_accordion_title' => $config['title'],
	'xlwcty_icon'            => 'xlwcty-fa xlwcty-fa-drivers-license-o',
	'is_multiple'            => true,
	'count'                  => 4,
	'fields'                 => array(
		/**
		 * START OF ELEMENT
		 */
		array(
			'name'                       => __( 'Enable', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'                         => $config['slug'] . '_enable_{{index}}',
			'type'                       => 'xlwcty_switch',
			'row_classes'                => array( 'xlwcty_is_enable' ),
			'label'                      => array(
				'on'  => __( 'Yes', 'thank-you-page-for-woocommerce-nextmove' ),
				'off' => __( 'No', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'before_row'                 => array( 'XLWCTY_Admin_CMB2_Support', 'cmb_before_row_cb' ),
			'xlwcty_accordion_title'     => $config['title'] . ' {{index}}',
			'xlwcty_accordion_index'     => '{{index}}',
			'xlwcty_component'           => $config['slug'],
			'xlwcty_is_accordion_opened' => false,
			'after'                      => include_once __DIR__ . '/help.php',
		),
		array(
			'name'        => __( 'Heading', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_heading_{{index}}',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_no_border' ),
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Heading font size', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_heading_font_size_{{index}}',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_combine_2_field_start' ),
			'before'      => '<p>Font Size (px)</p>',
			'attributes'  => array(
				'type'                   => 'number',
				'min'                    => '0',
				'pattern'                => '\d*',
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Heading alignment', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_heading_alignment_{{index}}',
			'type'        => 'select',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_combine_2_field_end' ),
			'before'      => '<p>Alignment</p>',
			'options'     => array(
				'left'   => __( 'Left', 'thank-you-page-for-woocommerce-nextmove' ),
				'center' => __( 'Center', 'thank-you-page-for-woocommerce-nextmove' ),
				'right'  => __( 'Right', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Description', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_desc_{{index}}',
			'type'        => 'textarea_small',
			'row_classes' => array( 'xlwcty_no_border' ),
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Description alignment', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_desc_alignment_{{index}}',
			'type'        => 'select',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_select_small' ),
			'before'      => '<p>Alignment</p>',
			'options'     => array(
				'left'   => __( 'Left', 'thank-you-page-for-woocommerce-nextmove' ),
				'center' => __( 'Center', 'thank-you-page-for-woocommerce-nextmove' ),
				'right'  => __( 'Right', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Layout', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_layout_{{index}}',
			'type'        => 'radio_inline',
			'options'     => array(
				'full'          => "<img src='//storage.googleapis.com/xl-nextmove/img/only_icon.jpg' />",
				'2c'            => "<img src='//storage.googleapis.com/xl-nextmove/img/icon-icon.jpg' />",
				'image_content' => "<img src='//storage.googleapis.com/xl-nextmove/img/icon-text.jpg' />",
				'content_image' => "<img src='//storage.googleapis.com/xl-nextmove/img/text-icon.jpg' />",
			),
			'row_classes' => array( 'xlwcty_img_options' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Image', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_img_source_{{index}}',
			'type'        => 'file',
			'options'     => array(
				'url' => false,
			),
			'text'        => array(
				'add_upload_file_text' => 'Add/ Update Image',
			),
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label' ),
			'before'      => '<p>Image</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => 'full',
			),
		),
		array(
			'name'        => __( 'Image link ', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_img_link_{{index}}',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_pt0', 'xlwcty_hide_label' ),
			'before'      => '<p>Link</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => 'full',
			),
		),
		array(
			'name'        => __( 'Image Content Ratio', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_img_cont_ratio_{{index}}',
			'type'        => 'radio_inline',
			'options'     => array(
				'50_50' => "<img src='//storage.googleapis.com/xl-nextmove/img/image_layout_50_50.jpg' />",
				'33_66' => "<img src='//storage.googleapis.com/xl-nextmove/img/image_layout_33_66.jpg' />",
				'66_33' => "<img src='//storage.googleapis.com/xl-nextmove/img/image_layout_66_33.jpg' />",
			),
			'row_classes' => array( 'xlwcty_img_options' ),
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => json_encode( array( 'image_content', 'content_image' ) ),
			),
		),
		array(
			'name'        => __( 'Left Image', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_img_l_source_{{index}}',
			'type'        => 'file',
			'options'     => array(
				'url' => false,
			),
			'text'        => array(
				'add_upload_file_text' => 'Add/ Update Imade',
			),
			'row_classes' => array( 'xlwcty_no_border' ),
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => json_encode( array( 'image_content', '2c' ) ),
			),
		),
		array(
			'name'        => __( 'Left Image link ', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_img_l_link_{{index}}',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p>Link</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => json_encode( array( 'image_content', '2c' ) ),
			),
		),
		array(
			'name'        => __( 'Content', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_editor_{{index}}',
			'row_classes' => array( 'xlwcty_no_border' ),
			'type'        => 'wysiwyg',
			'before_row'  => array( 'XLWCTY_Admin_CMB2_Support', 'before_wysiwyg' ),
			'after_row'   => array( 'XLWCTY_Admin_CMB2_Support', 'after_wysiwyg' ),
			'options'     => array(
				'wpautop'       => true,
				'media_buttons' => false,
				'tabindex'      => '',
				'textarea_rows' => 10,
				'editor_css'    => '',
				'editor_class'  => '',
				'teeny'         => false,
				'dfw'           => false,
				'tinymce'       => true,
				'quicktags'     => true,
			),
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => json_encode( array( 'image_content', 'content_image' ) ),
			),
		),
		array(
			'name'        => __( 'Right Image', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_img_r_source_{{index}}',
			'type'        => 'file',
			'options'     => array(
				'url' => false,
			),
			'text'        => array(
				'add_upload_file_text' => 'Add/ Update Imade',
			),
			'row_classes' => array( 'xlwcty_no_border' ),
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => json_encode( array( '2c', 'content_image' ) ),
			),
		),
		array(
			'name'        => __( 'Right Image link ', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_img_r_link_{{index}}',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p>Link</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_layout_{{index}}',
				'data-xlwcty-conditional-value' => json_encode( array( '2c', 'content_image' ) ),
			),
		),
		array(
			'name'        => __( 'Show Button', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_show_btn_{{index}}',
			'type'        => 'radio_inline',
			'options'     => array(
				'yes' => __( 'Yes', 'thank-you-page-for-woocommerce-nextmove' ),
				'no'  => __( 'No', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'row_classes' => array( 'xlwcty_no_border' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Button Text', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_text_{{index}}',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_no_border', 'xlwcty_pt0' ),
			'before'      => '<p>Text</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_show_btn_{{index}}',
				'data-xlwcty-conditional-value' => 'yes',
			),
		),
		array(
			'name'        => __( 'Button Link', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Use ', 'thank-you-page-for-woocommerce-nextmove' ) . ' {{home_url}}, {{shop_url}} ' . __( 'for dynamic links.', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_link_{{index}}',
			'desc'        => '<a href="javascript:void(0);" onclick="xlwcty_show_tb(\'Merge Tags\',\'xlwcty_merge_tags_invenotry_bar_help\');">Dynamic merge tags list</a>',
			'type'        => 'text',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
			'before'      => '<p>Link</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_show_btn_{{index}}',
				'data-xlwcty-conditional-value' => 'yes',
			),
		),
		array(
			'name'        => __( 'Button Font Size', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_font_size_{{index}}',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_combine_3_field_start' ),
			'before'      => '<p>Font Size (px)</p>',
			'attributes'  => array(
				'type'                          => 'number',
				'min'                           => '1',
				'pattern'                       => '\d*',
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_show_btn_{{index}}',
				'data-xlwcty-conditional-value' => 'yes',
			),
		),
		array(
			'name'        => __( 'Button Text Color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_color_{{index}}',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_combine_3_field_middle' ),
			'before'      => '<p>Text Color</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_show_btn_{{index}}',
				'data-xlwcty-conditional-value' => 'yes',
			),
		),
		array(
			'name'        => __( 'Button Background Color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_btn_bg_color_{{index}}',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0', 'xlwcty_combine_3_field_end' ),
			'before'      => '<p>Background Color</p>',
			'attributes'  => array(
				'data-conditional-id'           => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value'        => '1',
				'data-xlwcty-conditional-id'    => $config['slug'] . '_show_btn_{{index}}',
				'data-xlwcty-conditional-value' => 'yes',
			),
		),
		array(
			'name'        => __( 'Border', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_border_style_{{index}}',
			'type'        => 'select',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_select_small', 'xlwcty_combine_3_field_start' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Style</p>',
			'options'     => array(
				'dotted' => __( 'Dotted', 'thank-you-page-for-woocommerce-nextmove' ),
				'dashed' => __( 'Dashed', 'thank-you-page-for-woocommerce-nextmove' ),
				'solid'  => __( 'Solid', 'thank-you-page-for-woocommerce-nextmove' ),
				'double' => __( 'Double', 'thank-you-page-for-woocommerce-nextmove' ),
				'none'   => __( 'None', 'thank-you-page-for-woocommerce-nextmove' ),
			),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Border Width', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_border_width_{{index}}',
			'type'        => 'text_small',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_combine_3_field_middle' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Width (px)</p>',
			'attributes'  => array(
				'type'                   => 'number',
				'min'                    => '0',
				'pattern'                => '\d*',
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Border Color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_border_color_{{index}}',
			'type'        => 'colorpicker',
			'row_classes' => array( 'xlwcty_border_top', 'xlwcty_hide_label', 'xlwcty_combine_3_field_end' ),
			'before'      => '<p class="xlwcty_mt5 xlwcty_mb5">Color</p>',
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Background', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Component background color', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_component_bg_{{index}}',
			'type'        => 'colorpicker',
			'row_classes' => array(),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Hide on', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Desktop', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_hide_desktop_{{index}}',
			'type'        => 'checkbox',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_combine_2_field_start' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
		),
		array(
			'name'        => __( 'Hide on', 'thank-you-page-for-woocommerce-nextmove' ),
			'desc'        => __( 'Mobile', 'thank-you-page-for-woocommerce-nextmove' ),
			'id'          => $config['slug'] . '_hide_mobile_{{index}}',
			'type'        => 'checkbox',
			'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_combine_2_field_end' ),
			'attributes'  => array(
				'data-conditional-id'    => $config['slug'] . '_enable_{{index}}',
				'data-conditional-value' => '1',
			),
			'after_row'   => array( 'XLWCTY_Admin_CMB2_Support', 'cmb_after_row_cb' ),
		),
		/**
		 * END OF ELEMENT
		 */
	),
);
$config['default']  = array(
	'heading'            => '',
	'heading_font_size'  => '20',
	'heading_alignment'  => 'center',
	'desc'               => '',
	'desc_alignment'     => 'center',
	'layout'             => 'full',
	'img_source'         => '',
	'img_link'           => '',
	'img_cont_ratio'     => '50_50',
	'img_l_source'       => '',
	'img_l_link'         => '#',
	'editor'             => '',
	'show_btn'           => 'no',
	'btn_text'           => 'Start Shopping',
	'btn_link'           => '{{shop_url}}',
	'btn_font_size'      => '20',
	'btn_color'          => '#ffffff',
	'btn_bg_color'       => '#1291ff',
	'img_r_source'       => '',
	'img_r_link'         => '#',
	'border_style'       => 'solid',
	'border_width'       => '1',
	'border_color'       => '#d9d9d9',
	'component_bg_color' => '#ffffff',
);

return $config;
