<?php
defined( 'ABSPATH' ) || exit;

$ga_after_row_text_link = add_query_arg( array(
	'utm_source'   => 'nextmove-pro',
	'utm_campaign' => 'settings',
	'utm_medium'   => 'text-click',
	'utm_term'     => 'javascript-event',
), 'https://xlplugins.com/documentation/nextmove-woocommerce-thank-you-page/how-to/add-custom-javascript-events-thank-page/' );

$ga_after_row_text = '<h4>' . __( 'Already set up Facebook Pixel or Google Analytics Events? You <em>don\'t need to</em> check these settings. Just ensure that your Pixels/Events are triggered on NextMove Thank You Page(s).', 'thank-you-page-for-woocommerce-nextmove' );
$ga_after_row_text .= '<br/><br/>' . __( 'If you want to fire custom javascript events or thank you page, follow this', 'thank-you-page-for-woocommerce-nextmove' ) . ' <a href="' . $ga_after_row_text_link . '" target="_blank">link</a>.</h4>';

return apply_filters( 'xlwcty_setting', array(
	array(
		'name'       => __( 'NextMove Mode', 'thank-you-page-for-woocommerce-nextmove' ),
		'desc'       => __( 'Select Live button to go live. In <strong>Sandbox mode</strong>, only preview works.', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'         => 'xlwcty_preview_mode',
		'type'       => 'radio_inline',
		'options'    => array(
			'live'    => __( 'Live', 'thank-you-page-for-woocommerce-nextmove' ),
			'sandbox' => __( 'Sandbox', 'thank-you-page-for-woocommerce-nextmove' ),
		),
		'before_row' => '<h3>General</h3>',
	),
	array(
		'name'       => __( 'Left Right Padding (gap)', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'         => 'wrap_left_right_padding',
		'type'       => 'text',
		'desc'       => __( 'In responsive mode if you find left right padding is required', 'thank-you-page-for-woocommerce-nextmove' ),
		'attributes' => array(
			'type'    => 'number',
			'min'     => '0',
			'pattern' => '\d*',
		),
	),
	array(
		'name'        => __( 'Allow ThankYou pages on Order Status', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'allowed_order_statuses',
		'type'        => 'xlwcty_post_select',
		'row_classes' => array( 'xlwcty_cmb2_chosen', 'xlwcty_no_border' ),
		'options'     => XLWCTY_Admin_CMB2_Support::get_wc_order_statuses(),
		'desc'        => __( 'Note: If you are receiving payments using PayPal kindly enable "pending payment" in order statuses', 'thank-you-page-for-woocommerce-nextmove' ),
		'attributes'  => array(
			'multiple'         => 'multiple',
			'name'             => 'allowed_order_statuses[]',
			'data-placeholder' => __( 'Choose Order Status', 'thank-you-page-for-woocommerce-nextmove' ),
		),
	),
	array(
		'name'        => __( 'Facebook App ID', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'fb_app_id',
		'type'        => 'text',
		'desc'        => __( 'To generate new APP, <a href="https://developers.facebook.com/apps/" target="_blank">Click here</a> and press \'Add a New App\' button', 'thank-you-page-for-woocommerce-nextmove' ),
		'before_row'  => '<h3>Facebook</h3>',
		'row_classes' => array( 'xlwcty_no_border' ),
	),
	array(
		'name'       => __( 'Google Map Api Key', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'         => 'google_map_api',
		'type'       => 'text',
		'desc'       => __( 'To generate API key, <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" target="_blank">Click here</a>', 'thank-you-page-for-woocommerce-nextmove' ),
		'before_row' => '<h3>Google Map</h3>',
	),
	array(
		'name'        => __( 'Google Map Error Text', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'google_map_error_txt',
		'type'        => 'text',
		'desc'        => __( 'This text would be visible when map is unable to load', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border' ),
	),
	array(
		'name'       => __( 'Products Grid/List Thumbnail Size', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'         => 'shop_thumbnail_size',
		'type'       => 'select',
		'desc'       => __( 'That\'s the product image size used in Product list related components', 'thank-you-page-for-woocommerce-nextmove' ),
		'options'    => get_intermediate_image_sizes(),
		'before_row' => '<h3>Product Grids</h3>',
	),
	array(
		'name'        => __( 'Products Grid/List Button', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'shop_button_bg_color',
		'type'        => 'colorpicker',
		'row_classes' => array( 'xlwcty_combine_2_field_start' ),
		'before'      => '<p>Background Color</p>',
	),
	array(
		'name'        => __( 'Products Grid/List Button', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'shop_button_text_color',
		'type'        => 'colorpicker',
		'row_classes' => array( 'xlwcty_hide_label', 'xlwcty_combine_2_field_end', 'xlwcty_no_border' ),
		'before'      => '<p>Text Color</p>',
	),
	array(
		'name'        => __( 'Allow Free Shipping', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'allow_free_shipping',
		'desc'        => __( 'Check this box if the coupon associated with Smart Bribe or Dynamic Coupon grants free shipping. A free shipping method must be enabled in your shipping zone and be set to require "a valid free shipping coupon" (see the "Free Shipping Requires" setting).', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border' ),
		'default'     => '',
		'type'        => 'checkbox',
		'before_row'  => '<h3>Personalized Coupons</h3>',
	),
	array(
		'name'        => __( 'Free Shipping On', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'restrict_free_shipping',
		'type'        => 'radio_inline',
		'row_classes' => array( 'xlwcty_no_border', 'xlwcty_pt0', 'xlwcty_hide_label' ),
		'options'     => array(
			'yes' => __( 'Specific Order Status', 'thank-you-page-for-woocommerce-nextmove' ),
			'no'  => __( 'All Order Status', 'thank-you-page-for-woocommerce-nextmove' ),
		),
		'default'     => 'yes',
		'before'      => '<p>Free Shipping On</p>',
		'attributes'  => array(
			'data-conditional-id'    => 'allow_free_shipping',
			'data-conditional-value' => 'on',
		),
	),
	array(
		'name'        => __( 'Order Status', 'thank-you-page-for-woocommerce-nextmove' ),
		'desc'        => __( 'Free Shipping on these coupons will only be available when above order status is present in user\'s last order.', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'allowed_order_statuses_coupons',
		'type'        => 'xlwcty_post_select',
		'row_classes' => array( 'xlwcty_cmb2_chosen', 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'before'      => '<p>Order Status</p>',
		'options'     => XLWCTY_Admin_CMB2_Support::get_wc_order_statuses(),
		'attributes'  => array(
			'multiple'                      => 'multiple',
			'name'                          => 'allowed_order_statuses_coupons[]',
			'data-placeholder'              => __( 'Choose Order Status', 'thank-you-page-for-woocommerce-nextmove' ),
			'data-conditional-id'           => 'allow_free_shipping',
			'data-conditional-value'        => 'on',
			'data-xlwcty-conditional-id'    => 'restrict_free_shipping',
			'data-xlwcty-conditional-value' => 'yes',
		),
	),
	array(
		'name'        => __( 'Coupon Blur Intensity', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'coupon_blur',
		'type'        => 'text',
		'desc'        => __( 'Set Blur intensity in Social Share or Dynamic Coupons component before creating an actual Coupon.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border' ),
		'default'     => '2',
		'attributes'  => array(
			'type'    => 'number',
			'min'     => '0',
			'max'     => '10',
			'pattern' => '\d*',
		),
	),
	array(
		'name'        => __( 'Enable SKU', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'append_sku_order_url',
		'desc'        => __( 'Check this box if you want to append SKU in Order Thank You URL.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border' ),
		'default'     => '',
		'type'        => 'checkbox',
		'before_row'  => '<h3>Advanced Settings</h3>',
	),
	array(
		'name'            => __( 'SKU key in Order URL', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'              => 'append_sku_order_url_key',
		'row_classes'     => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'before'          => '<p>SKU key in Order URL</p>',
		'type'            => 'text',
		'sanitization_cb' => array( 'XLWCTY_Common', 'cmb2_sanitize_text' ),
		'display_cb'      => array( 'XLWCTY_Common', 'cmb2_sanitize_text' ),
		'attributes'      => array(
			'data-conditional-id'    => 'append_sku_order_url',
			'data-conditional-value' => 'on',
		),
	),
	array(
		'name'        => __( 'Enable Order Total', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'append_order_total_order_url',
		'desc'        => __( 'Check this box if you want to append Order Total in Order Thank You URL.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border' ),
		'default'     => '',
		'type'        => 'checkbox',
	),
	array(
		'name'            => __( 'Order Total key in Order URL', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'              => 'append_order_total_order_url_key',
		'row_classes'     => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'before'          => '<p>Order Total key in Order URL</p>',
		'type'            => 'text',
		'sanitization_cb' => array( 'XLWCTY_Common', 'cmb2_sanitize_text' ),
		'display_cb'      => array( 'XLWCTY_Common', 'cmb2_sanitize_text' ),
		'attributes'      => array(
			'data-conditional-id'    => 'append_order_total_order_url',
			'data-conditional-value' => 'on',
		),
	),
	array(
		'name'        => __( 'Enable Facebook Pixel Tracking', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'enable_fb_ecom_tracking',
		'desc'        => __( 'Check this box if you want to fire Facebook Pixels Events on Thank You page.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border' ),
		'default'     => '',
		'type'        => 'checkbox',
		'before_row'  => '<h3>eCommerce Tracking Codes</h3>',
	),
	array(
		'name'        => __( 'Facebook Pixel ID', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'ga_fb_pixel_id',
		'desc'        => __( 'Log into your facebook ads account to find your Pixel ID. <a href="https://www.facebook.com/ads/manager/pixel/facebook_pixel" target="_blank">Click here for more info</a>.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'before'      => '<p>Facebook Pixel ID</p>',
		'type'        => 'text',

		'attributes' => array(
			'data-conditional-id'    => 'enable_fb_ecom_tracking',
			'data-conditional-value' => 'on',
		),
	),
	array(
		'name'        => __( 'Fire Facebook PageView event', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'enable_fb_pageview_event',
		'desc'        => __( 'Fire Facebook PageView event', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'type'        => 'checkbox',
		'default'     => '',
		'attributes'  => array(
			'data-conditional-id'    => 'enable_fb_ecom_tracking',
			'data-conditional-value' => 'on',
		),
	),
	array(
		'name'        => __( 'Fire Facebook Purchase event to Add Conversion Values', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'enable_fb_purchase_event_conversion_val',
		'desc'        => __( 'Fire Facebook Purchase event to Add Conversion Values', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'type'        => 'checkbox',
		'default'     => '',
		'attributes'  => array(
			'data-conditional-id'    => 'enable_fb_ecom_tracking',
			'data-conditional-value' => 'on',
		),
		'after'       => __( '<p>Note: NextMove will send total order value and store currency based on order. <a href="https://developers.facebook.com/docs/facebook-pixel/pixel-with-ads/conversion-tracking#add-value" target="_blank">Click here</a> to know more.</p>', 'thank-you-page-for-woocommerce-nextmove' ),
	),
	array(
		'name'        => __( 'Fire Facebook Purchase event with Order item\'s complete data i.e. product name, category & product_id.', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'enable_fb_purchase_event',
		'desc'        => __( 'Fire Facebook Purchase event with Order item\'s complete data i.e. product name, category & product_id.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'type'        => 'checkbox',
		'default'     => '',
		'attributes'  => array(
			'data-conditional-id'    => 'enable_fb_ecom_tracking',
			'data-conditional-value' => 'on',
		),
		'after'       => __( '<p>Note: Your Product catalog must be synced with Facebook. <a href="https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog" target="_blank">Click here</a> to know more.</p>', 'thank-you-page-for-woocommerce-nextmove' ),
	),
	array(
		'name'        => __( 'Setup advanced matching with the pixel', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'enable_fb_advanced_matching_event',
		'desc'        => __( 'Setup advanced matching with the pixel', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'type'        => 'checkbox',
		'default'     => '',
		'attributes'  => array(
			'data-conditional-id'    => 'enable_fb_ecom_tracking',
			'data-conditional-value' => 'on',
		),
		'after'       => __( '<p>Note: NextMove will send customer\'s email, name, phone, address fields whichever available in the order. <a href="https://developers.facebook.com/docs/facebook-pixel/pixel-with-ads/conversion-tracking#advanced_match" target="_blank">Click here</a> to know more.</p>', 'thank-you-page-for-woocommerce-nextmove' ),
	),
	array(
		'name'        => __( 'Enable Google Analytics Tracking', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'enable_ga_ecom_tracking',
		'desc'        => __( 'Check this box if you want to push google analytics eCommerce events on Thank You page.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border' ),
		'default'     => '',
		'type'        => 'checkbox',
	),
	array(
		'name'        => __( 'Google Analytics ID', 'thank-you-page-for-woocommerce-nextmove' ),
		'id'          => 'ga_analytics_id',
		'desc'        => __( 'Log into your google analytics account to <a href="https://support.google.com/analytics/answer/1008080?hl=en#trackingID" target="_blank">find your ID</a>. eg: UA-XXXXXX-X.', 'thank-you-page-for-woocommerce-nextmove' ),
		'row_classes' => array( 'xlwcty_no_border', 'xlwcty_hide_label', 'xlwcty_pt0' ),
		'before'      => '<p>Google Analytics ID</p>',
		'after_row'   => $ga_after_row_text,
		'type'        => 'text',
		'attributes'  => array(
			'data-conditional-id'    => 'enable_ga_ecom_tracking',
			'data-conditional-value' => 'on',
		),
	),
	array(
		'name'       => '_wpnonce',
		'id'         => '_wpnonce',
		'type'       => 'hidden',
		'attributes' => array(
			'value' => wp_create_nonce( 'woocommerce-settings' ),
		),
	),
) );
