<?php $get_hash = $this->get_localstorage_hash( 'fb' ); ?>
    var wfocuFBHash = '<?php echo $get_hash; ?>';
    var wfocuFBResult = false;
    try {

    if ('1' === localStorage.getItem("wfocuH_" + wfocuFBHash)) {
    wfocuFBResult = true;
    }

    } catch (exception) {

    }

    if(false === wfocuFBResult) {
<?php
if ( $this->do_track_fb_synced_purchase() && is_array( $data ) && isset( $data['fb'] ) ) {
			?>
            var wfocufbDataPurchaseTrackSynced = {
            contents: <?php echo wp_json_encode( array_values( $data['fb']['products'] ) ); ?>,
            content_type: 'product',
            content_ids: <?php echo wp_json_encode( $data['fb']['content_ids'] ); ?>,
            value: <?php echo esc_js( $data['fb']['total'] ); ?>,
            currency: '<?php echo esc_js( $data['fb']['currency'] ); ?>',
            content_name: <?php echo wp_json_encode( implode( ',', $data['fb']['content_name'] ) ); ?>,
            category_name: <?php echo wp_json_encode( implode( ',', $data['fb']['category_name'] ) ); ?>,
            num_items: <?php echo esc_js( $data['fb']['num_qty'] ); ?>,
            transaction_id: '<?php echo esc_js( $data['fb']['transaction_id'] ); ?>'
            };

			<?php if ( isset( $data['fb']['additional']['town'] ) && ! empty( $data['fb']['additional']['town'] ) ) { ?>
                wfocufbDataPurchaseTrackSynced.town = '<?php echo esc_js( $data['fb']['additional']['town'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['country'] ) && ! empty( $data['fb']['additional']['country'] ) ) { ?>
                wfocufbDataPurchaseTrackSynced.country = '<?php echo esc_js( $data['fb']['additional']['country'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['state'] ) && ! empty( $data['fb']['additional']['state'] ) ) { ?>
                wfocufbDataPurchaseTrackSynced.state = '<?php echo esc_js( $data['fb']['additional']['state'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['payment'] ) && ! empty( $data['fb']['additional']['payment'] ) ) { ?>
                wfocufbDataPurchaseTrackSynced.payment = '<?php echo esc_js( $data['fb']['additional']['payment'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['shipping'] ) && ! empty( $data['fb']['additional']['shipping'] ) ) { ?>
                wfocufbDataPurchaseTrackSynced.shipping = '<?php echo esc_js( $data['fb']['additional']['shipping'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['coupon_name'] ) && ! empty( $data['fb']['additional']['coupon_name'] ) ) { ?>
                wfocufbDataPurchaseTrackSynced.coupon_name = '<?php echo esc_js( $data['fb']['additional']['coupon_name'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['coupon_used'] ) && ! empty( $data['fb']['additional']['coupon_used'] ) ) { ?>
                wfocufbDataPurchaseTrackSynced.coupon_used = '<?php echo esc_js( $data['fb']['additional']['coupon_used'] ); ?>';
			<?php } ?>
            wfocufbDataPurchaseTrackSynced = (typeof wfocuAddTrafficParamsToEvent !== "undefined")?wfocuAddTrafficParamsToEvent(wfocufbDataPurchaseTrackSynced,'fb','<?php echo wp_json_encode( $this->get_generic_event_params() ); ?>'):wfocufbDataPurchaseTrackSynced;
            fbq('track', 'Purchase', wfocufbDataPurchaseTrackSynced);

			<?php
		}

		if ( false === $this->do_track_fb_synced_purchase() && $this->do_track_fb_purchase_event() && is_array( $data ) && isset( $data['fb'] ) ) {
			?>
            var wfocufbDataPurchaseTrack = {
            'value': '<?php echo esc_js( $data['fb']['total'] ); ?>',
            'currency': '<?php echo esc_js( $data['fb']['currency'] ); ?>',
            'content_name': <?php echo wp_json_encode( implode( ',', $data['fb']['content_name'] ) ); ?>,
            'category_name': <?php echo wp_json_encode( implode( ',', $data['fb']['category_name'] ) ); ?>,
            'num_items': <?php echo esc_js( $data['fb']['num_qty'] ); ?>,
            'transaction_id': '<?php echo esc_js( $data['fb']['transaction_id'] ); ?>'
            };
           wfocufbDataPurchaseTrack = (typeof wfocuAddTrafficParamsToEvent !== "undefined")?wfocuAddTrafficParamsToEvent(wfocufbDataPurchaseTrack,'fb','<?php echo wp_json_encode( $this->get_generic_event_params() ); ?>'):wfocufbDataPurchaseTrack;

			<?php if ( isset( $data['fb']['additional']['town'] ) && ! empty( $data['fb']['additional']['town'] ) ) { ?>
                wfocufbDataPurchaseTrack.town = '<?php echo esc_js( $data['fb']['additional']['town'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['country'] ) && ! empty( $data['fb']['additional']['country'] ) ) { ?>
                wfocufbDataPurchaseTrack.country = '<?php echo esc_js( $data['fb']['additional']['country'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['state'] ) && ! empty( $data['fb']['additional']['state'] ) ) { ?>
                wfocufbDataPurchaseTrack.state = '<?php echo esc_js( $data['fb']['additional']['state'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['payment'] ) && ! empty( $data['fb']['additional']['payment'] ) ) { ?>
                wfocufbDataPurchaseTrack.payment = '<?php echo esc_js( $data['fb']['additional']['payment'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['shipping'] ) && ! empty( $data['fb']['additional']['shipping'] ) ) { ?>
                wfocufbDataPurchaseTrack.shipping = '<?php echo esc_js( $data['fb']['additional']['shipping'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['coupon_name'] ) && ! empty( $data['fb']['additional']['coupon_name'] ) ) { ?>
                wfocufbDataPurchaseTrack.coupon_name = '<?php echo esc_js( $data['fb']['additional']['coupon_name'] ); ?>';
			<?php } ?>
			<?php if ( isset( $data['fb']['additional']['coupon_used'] ) && ! empty( $data['fb']['additional']['coupon_used'] ) ) { ?>
                wfocufbDataPurchaseTrack.coupon_used = '<?php echo esc_js( $data['fb']['additional']['coupon_used'] ); ?>';
			<?php } ?>

            fbq('track', 'Purchase', wfocufbDataPurchaseTrack);
			<?php
		} ?>
try {

localStorage.setItem("wfocuH_" + wfocuFBHash, "1");

} catch (exception) {

}
}
